version: 0.1
# brent lemons 20191028

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew build
  post_build:
    commands:
      - aws cloudformation package --output-template-file outputtemplate.yaml --template-file template.yaml --s3-bucket bkl-test-starter

artifacts:
  files:
    - outputtemplate.yaml
  discard-paths: yes