AWSTemplateFormatVersion: '2010-09-09'
Description: Template describing the service infrastructure
Parameters:
  CodeCommitRepoName:
    Type: String
Resources:
  IamRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-test-starter/5a2a38c1c85acd008aca053c0dc5f70d.template
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-test-starter/ef4867b7f62eb3b857371b384fb060f3.template
      Parameters:
        ArtifactBucketName:
          Fn::GetAtt:
          - IamRoles
          - Outputs.ArtifactBucketName
        CodePipelineServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodePipelineServiceRoleArn
        CodeBuildServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodeBuildServiceRoleArn
        CodeCommitRepositoryName:
          Ref: CodeCommitRepoName
        CodeCommitBranchName: master
